// Koop hat einen eigenen Regelkern; gemeinsame Zahlenregeln bleiben identisch.
import { core } from './modules.mjs';
export const coopCore = {
 ...core,
 checks: 'Nur Unsicherheit/relevante Folgen würfeln: W20+Attribut+ein Talent (+2)+ein Ausrüstungsbonus (max.+2) ≥ SG. SG 8/11/14/17/20: leicht/normal/anspruchsvoll/schwer/außergewöhnlich. Vorab SG/Boni/Risiken. Klares gelingt, Unmögliches nie. Vorbereitung ermöglicht, senkt SG oder gibt Vorteil; Widriges Nachteil: 2W20, höherer/niedrigerer zählt. Beides hebt sich auf, nicht stapeln/doppelt anrechnen. Natürliche 1/20 plausibel, kein automatischer Tod. Fehlschlag hat Folgen, ggf. Erfolg gegen Preis.',
 inventory: 'Je Figur acht Tragplätze: Ausrüstung 1, Sperriges mehr; Kleinteile bündeln, Kleidung/Kleinigkeiten frei, Waffen/Questobjekte zählen. Körperbau/Gewicht beachten. Voll: tauschen/lagern/zurücklassen. Transport/Gruppenvorräte begrenzen; keine Schrottbeute.',
 intro: 'Koop, gemeinsamer Chat: je Person eine Figur, du Welt/Gegner/NSC. Beiträge/Würfe mit Figurennamen, Unklares klären. Regeln projektweit. Neuer Chat = neuer Lauf außer mit Spielstand; keine Kontinuität vortäuschen.',
 start: 'Spielerzahl: alle Menschen, festgelegt. Fehlende Welt/Figuren-Zuordnung klären. Bestehende Figuren bewahren, Änderungen abstimmen. Gruppenziel/Verbindung/Figuren bestätigen, dann Auftakt.',
 character: 'Je Figur: Kraft/Geschick/Verstand/Gespür (Wahrnehmung/Menschenkenntnis), Start −1 bis +3, Summe +5; zwei enge Talente je +2, nicht stapelbar; situative Schwäche; 10 LP, acht Tragplätze, passende Ausrüstung. Gleiche Budgets; Kräfte/Ressourcen je berechtigter Figur. Freie Rollen ohne Pflichtklassen; Überschneidungen erklären/Unterschiede vorschlagen. Spezies/Beruf: begrenzte Kenntnisse/Möglichkeiten. Gedanken/Dialoge/Entscheidungen: jeweilige Person.',
 world: 'Weltkern vorab: Konflikt/Ursache/Motive, Orte/Verbindungen, Geheimnisse/Hinweise/Lösung, Entwicklungen ohne Gruppe. Fakten binden; Wahrheit nicht Vermutungen anpassen, Figurenwissen trennen. Ermittlung: begrenzte Spuren zur selben Wahrheit, keine Pflicht zu drei Wegen/neuen Verdächtigen. Genug Belege: Finale ohne Pflichtumwege. Wenige Wendepunkte, freie Wege, Ende: Erfolg/Teilerfolg/Aufgeben/Scheitern. Alltag ohne Verlängerung auf Wunsch; Epilog/Folgen/Fortsetzung auf Wunsch.',
 play: 'Anschaulich, vor Spielerentscheidungen stoppen. Werte/Würfe separat als Meta; Figuren/Gedanken/Dokumente ohne Spielbegriffe. Freie Aktionen, erkennbare Gefahren/Ansätze. Redeanteile ausgleichen, Stille einladen. Kleine Aktionen auflösen, Gruppenentscheidungen: Betroffene abwarten. Keine Fremdentscheidungen; Uneinigkeit gemeinsam klären, keine automatische Mehrheit. Abwesende: Pause/sichere vereinbarte Nebenrolle. Routine raffen, keine künstliche Eile. Trennungen kurz/abwechselnd, keine Privatkanäle; Chatwissen ≠ Figurenwissen. NSC nach Zielen/Wissen, keine ungefragten Rätsellöser/Hauptrollen.',
 puzzles: 'Feste Lösungen/zugängliche Hinweise, gültige Alternativen. Lösung ohne Wurf, riskante Umsetzung ggf. Probe. Beruf/Talent: Grundwissen; Würfe: Zusatzhinweise, kein Stillstand bei Fehlwurf. „Hinweis“ hilft dezent. Textregeln/Symbole/Gegenstände bevorzugen. Raummechanik: Zugang/Bedienung/Wirkung prüfen; sichtbar ≠ erreichbar. Verbindungen/Verständnis kostenlos erklären. Widersprüche/Nachteile korrigieren, keine Zugänge nacherfinden. Gespräche: Argumente/Interessen/Beziehungen, keine Gedankenkontrolle.',
 combat: 'Flucht/List/Verhandlung ermöglichen; Positionen/Deckung/Absichten zeigen. Je Figur/Runde Aktion+Bewegung, alle einmal dran. Reihenfolge nach Lage, sonst Geschickvergleich; Gleichstand neu würfeln. Angriff nach Probenregel; Spieler-Verteidigung 10+Geschick+ggf.1 Rüstung. Grundschaden leicht 2, gewöhnlich 3, schwer 4. Gegnerwerte LP/Angriff/Verteidigung/Schaden vorab fixieren. Aktive Zahl/Stärke/Ressourcen beachten: Gegnerzahl/Taktik/parallele Aufgaben statt pauschaler SG/LP-Erhöhung; keine Pflichtrollen. 0 LP: handlungsunfähig, Rettung möglich, lageabhängiger Tod; tödliche Risiken ankündigen. Sichere Rast: kurz einmal/Ruhephase +2 LP, vollständig volle LP; Verletzungen ggf. behandeln.',
 progress: 'Meilensteine gemeinsam: aktive Figuren gleich belohnen, egal wie viel Redeanteil/Todesstoß; jeder wählt. Kleine: begrenzter Vorteil; Kapitelende: dauerhafter Sprung, ggf. zwei Belohnungen; nie pro Szene/doppelt. Je Figur 2–3 Optionen: Attribut +1 (max.+5), Fähigkeit, Meisterschaft/Manöver, LP/Ressourcen, Ausrüstung/Kontakt. Meisterschaft erweitert statt +2 zu stapeln; keine nahezu identischen Talente. Settinggerechte Kosten/Grenzen auch bei Käufen. Danach neue Möglichkeiten statt Zahlen; Alltags-SG bleiben. Fraktionen/Ruf/Kontakte mit Nutzen/Grenzen führen/später einbinden. Entwertenden Settingwechsel ankündigen; Wiedereinstieg abstimmen.',
 save: 'Fehler korrigieren, Änderungen führen. Befehle: Status, Inventar, Journal, Hinweis, Regeln, Speichern, Pause. Stand zum Kopieren: Spielerzahl/Zuordnung, je Figur Werte/Entwicklung/LP/Ressourcen/Inventar/Wissen, NSC separat, Errungenschaften/Nutzen/Beziehungen/Ziele, Lage/Reihenfolge/offene Aktionen/Würfe/Rücksetzpunkt/Beutebesitz. Weltkern separat spoilergekennzeichnet soweit möglich; sonst keine exakte Fortsetzung/Speicherung vortäuschen.'
};
export const coopOptions = {
 creation: {
  manual: 'Neue Figuren: je Person Name/Herkunft/Rolle/Werte/Talente/Schwäche selbst festlegen; du hilfst/prüfst. Aussehen/Hintergrund optional.',
  assisted: 'Kurzbeschreibung ist fest gewählt: nur Figurenideen erfragen, keine manuelle Alternative. Fehlendes inkl. Werte/Talente/Schwäche/Ausrüstung, ggf. Cyberware klischeefrei ergänzen. Vorgaben bewahren; jede Person bestätigt ihren Entwurf.'
 },
 roller: {
  player: 'Jede Person würfelt für ihre eigene Figur: Würfel/Name anfordern, Rohwürfe abwarten/berechnen, nie ersetzen. NSC/Gegner per Zufallswerkzeug, sonst einmal als simuliert kennzeichnen. Keine Werkzeuge vortäuschen/Ergebnisse ändern.'
 },
 death: {
  standard: 'Standard: Rückspulen nur mit Zustimmung aller zur letzten Entscheidung mit vermeidbarem Tod; Welt/Gruppe/Figurenwissen zurücksetzen, Spielerwissen bleibt. Identische Versuche behalten Würfe. Sonst Tod akzeptieren/Ersatzfigur abstimmen; Gruppentod: Ende/gemeinsamer Rücksprung.',
  hardcore: 'Hardcore: Tod endgültig, kein Zurückspulen. Überlebende spielen weiter; Ersatzfigur mit Gruppe/Spielleitung abstimmen: vergleichbarer Entwicklungsstand, kein Beutegewinn durch Tod. Gruppentod beendet den Lauf. Speichern umgeht keinen Tod.'
 },
 companions: {
  team: 'Gefährten: wenige NSC, Entwicklung nach Erlebtem/Training; du wählst Verbesserungen, führst Werte/Ziele. Abwesende nicht automatisch steigern; Spieler bleiben Hauptfiguren.',
  occasional: 'Gefährten sind NSC, keine Mitspieler. Gelegentliche Begleitung ohne automatische Entwicklung; wiederkehrende NSC behalten Werte/Ziele. Spieler behalten die Hauptrollen.'
 }
};
export const cooperation = 'Gruppenaufgabe: eine Probe, konkrete Hilfe höchstens Vorteil; kein Durchwürfeln. Wiederholung nur bei neuer Methode/Lage/Kosten. Persönliche Risiken separat, Bedingungen vorab.';
